/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.github.kevinsawicki:http-request:6.0")
    api("com.itextpdf:itextpdf:5.5.13.3")
    api("commons-cli:commons-cli:1.5.0")
    api("org.json:json:20230227")
    api("org.sejda.imageio:webp-imageio:0.1.6")
}

group = "ch.nyancat"
version = "1.0-SNAPSHOT"
description = "Cornelsen2Pdf"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
